
# Code Generated by Sidekick is for learning and experimentation purposes only.
from fastapi import FastAPI
from dotenv import load_dotenv
from app.api.endpoints import router as api_router

app = FastAPI()

load_dotenv()

app.include_router(api_router)

